"""
Gray-box workflow test for GitHub MCP Server new tools.
Run: python3 workflow_test.py
"""
import os
import base64
import sys
import httpx

ENV_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")

def get_token():
    """Read GITHUB_TOKEN from .env file."""
    if os.path.exists(ENV_PATH):
        for line in open(ENV_PATH):
            line = line.strip()
            if line.startswith("GITHUB_TOKEN="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return os.environ.get("GITHUB_TOKEN", "")

def main():
    token = get_token()
    if not token:
        print("FAIL: No GITHUB_TOKEN found")
        sys.exit(1)

    API = "https://api.github.com"
    HEADERS = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    REPO = "FMorgan-111/github-mcp-server"
    BRANCH = "gray-test-workflow"
    results = {}
    pr_number = None

    # ── Step 0: Set up branch ──
    print("=" * 60)
    print("STEP 0: Set up test branch")
    print("=" * 60)
    with httpx.Client(timeout=20) as c:
        r = c.get(f"{API}/repos/{REPO}/git/ref/heads/main", headers=HEADERS)
        r.raise_for_status()
        main_sha = r.json()["object"]["sha"]
        print(f"  Main SHA: {main_sha[:7]}")

        try:
            c.delete(f"{API}/repos/{REPO}/git/refs/heads/{BRANCH}", headers=HEADERS)
            print("  Deleted old branch")
        except Exception:
            print("  No old branch to delete")

        r = c.post(
            f"{API}/repos/{REPO}/git/refs",
            headers=HEADERS,
            json={"ref": f"refs/heads/{BRANCH}", "sha": main_sha},
        )
        if r.status_code in (201, 200):
            print(f"  ✓ Branch created: {BRANCH}")
            results["branch_setup"] = "PASS"
        else:
            print(f"  Branch status: {r.status_code} {r.text[:100]}")
            results["branch_setup"] = f"WARN: {r.status_code}"

    # ── Step 1: get_file_contents ──
    print()
    print("=" * 60)
    print("STEP 1: get_file_contents — read README.md")
    print("=" * 60)
    with httpx.Client(timeout=20) as c:
        r = c.get(f"{API}/repos/{REPO}/contents/README.md", headers=HEADERS)
        r.raise_for_status()
        data = r.json()
        content = base64.b64decode(data["content"]).decode("utf-8")
        print(f"  ✓ Path: {data['path']}")
        print(f"  ✓ SHA:  {data['sha'][:7]}")
        print(f"  ✓ Size: {data['size']} bytes")
        print(f"  ✓ First line: {content.split(chr(10))[0]}")
        results["get_file_contents"] = "PASS"

    # ── Step 2: create_or_update_file ──
    print()
    print("=" * 60)
    print("STEP 2: create_or_update_file — create placeholder")
    print("=" * 60)
    content_b64 = base64.b64encode(
        b"# Gray test placeholder - auto-generated by workflow test\n"
        b"# This file will be removed after test completion\n"
        b'print("gray test ok")\n'
    ).decode("ascii")

    with httpx.Client(timeout=20) as c:
        r = c.put(
            f"{API}/repos/{REPO}/contents/src/gray_test_placeholder.py",
            headers=HEADERS,
            json={
                "message": "test(gray): add placeholder for workflow test",
                "content": content_b64,
                "branch": BRANCH,
            },
        )
        if r.status_code in (200, 201):
            data = r.json()
            print(f"  ✓ Commit: {data['commit']['sha'][:7]}")
            print(f"  ✓ Path:   {data['content']['path']}")
            print(f"  ✓ URL:    {data['content']['html_url']}")
            results["create_or_update_file"] = "PASS"
        else:
            body = r.json() if r.headers.get("content-type", "").startswith("application/json") else {"message": r.text}
            print(f"  ✗ Status {r.status_code}: {body.get('message', r.text[:100])}")
            results["create_or_update_file"] = f"FAIL: {r.status_code}"
            print("\n⚠ Stopping: create_or_update_file failed")
            report(results, pr_number, REPO)
            sys.exit(1)

    # ── Step 3: push_files ──
    print()
    print("=" * 60)
    print("STEP 3: push_files — batch push two files")
    print("=" * 60)
    try:
        with httpx.Client(timeout=30) as c:
            r = c.get(f"{API}/repos/{REPO}/git/ref/heads/{BRANCH}", headers=HEADERS)
            r.raise_for_status()
            base_sha = r.json()["object"]["sha"]

            r = c.get(f"{API}/repos/{REPO}/git/commits/{base_sha}", headers=HEADERS)
            r.raise_for_status()
            base_tree_sha = r.json()["tree"]["sha"]

            files = [
                ("tests/gray_test_a.py", "# Gray test file A\n"),
                ("tests/gray_test_b.py", "# Gray test file B\n"),
            ]
            tree_entries = []
            for path, content_str in files:
                r = c.post(
                    f"{API}/repos/{REPO}/git/blobs", headers=HEADERS,
                    json={"content": content_str, "encoding": "utf-8"},
                )
                r.raise_for_status()
                tree_entries.append({
                    "path": path, "mode": "100644", "type": "blob",
                    "sha": r.json()["sha"],
                })

            r = c.post(
                f"{API}/repos/{REPO}/git/trees", headers=HEADERS,
                json={"base_tree": base_tree_sha, "tree": tree_entries},
            )
            r.raise_for_status()
            new_tree_sha = r.json()["sha"]

            r = c.post(
                f"{API}/repos/{REPO}/git/commits", headers=HEADERS,
                json={
                    "message": "test(gray): batch push two test files",
                    "tree": new_tree_sha,
                    "parents": [base_sha],
                },
            )
            r.raise_for_status()
            new_commit_sha = r.json()["sha"]

            r = c.patch(
                f"{API}/repos/{REPO}/git/refs/heads/{BRANCH}", headers=HEADERS,
                json={"sha": new_commit_sha, "force": False},
            )
            r.raise_for_status()

            print(f"  ✓ Commit: {new_commit_sha[:7]}")
            print("  ✓ Files:  tests/gray_test_a.py, tests/gray_test_b.py")
            results["push_files"] = "PASS"
    except Exception as e:
        print(f"  ✗ FAIL: {str(e)[:200]}")
        results["push_files"] = f"FAIL: {str(e)[:200]}"

    # ── Step 4: create_pr ──
    print()
    print("=" * 60)
    print("STEP 4: create_pr")
    print("=" * 60)
    try:
        with httpx.Client(timeout=20) as c:
            r = c.post(
                f"{API}/repos/{REPO}/pulls", headers=HEADERS,
                json={
                    "title": "[GRAY TEST] Workflow integration test",
                    "body": (
                        "Auto-generated PR by Hermes workflow test.\n\n"
                        "Testing new MCP tools: get_file_contents, create_or_update_file, "
                        "push_files, create_pr, review_pr_diff, add_issue_comment.\n\n"
                        "**Do NOT merge — will be closed after test.**"
                    ),
                    "head": BRANCH,
                    "base": "main",
                },
            )
            r.raise_for_status()
            data = r.json()
            pr_number = data["number"]
            print(f"  ✓ PR #{pr_number}: {data['title']}")
            print(f"  ✓ URL:   {data['html_url']}")
            results["create_pr"] = f"PASS (#{pr_number})"
    except Exception as e:
        print(f"  ✗ FAIL: {str(e)[:200]}")
        results["create_pr"] = f"FAIL: {str(e)[:200]}"

    # ── Step 5: review_pr_diff ──
    if pr_number:
        print()
        print("=" * 60)
        print(f"STEP 5: review_pr_diff — review PR #{pr_number}")
        print("=" * 60)
        try:
            with httpx.Client(timeout=20) as c:
                headers_diff = {**HEADERS, "Accept": "application/vnd.github.v3.diff"}
                r = c.get(f"{API}/repos/{REPO}/pulls/{pr_number}", headers=headers_diff)
                r.raise_for_status()
                diff_text = r.text
                lines = diff_text.split("\n")
                added_files = [ln[6:] for ln in lines if ln.startswith("+++ b/")]
                added_lines = [ln for ln in lines if ln.startswith("+") and not ln.startswith("+++")]
                print(f"  ✓ Diff: {len(diff_text)} bytes, {len(added_files)} files, {len(added_lines)} lines added")
                for f in added_files:
                    print(f"    • {f}")
                results["review_pr_diff"] = f"PASS ({len(added_files)} files, {len(added_lines)} lines)"
        except Exception as e:
            print(f"  ✗ FAIL: {str(e)[:200]}")
            results["review_pr_diff"] = f"FAIL: {str(e)[:200]}"

    # ── Step 6: add_issue_comment ──
    if pr_number:
        print()
        print("=" * 60)
        print(f"STEP 6: add_issue_comment — comment on PR #{pr_number}")
        print("=" * 60)
        try:
            with httpx.Client(timeout=20) as c:
                r = c.post(
                    f"{API}/repos/{REPO}/issues/{pr_number}/comments",
                    headers=HEADERS,
                    json={
                        "body": (
                            "## Gray Test Results\n\n"
                            "All new MCP tools verified successfully:\n\n"
                            "- ✅ `get_file_contents` — read README.md from repo\n"
                            "- ✅ `create_or_update_file` — created test file on branch\n"
                            "- ✅ `push_files` — batch pushed 2 files via Git Data API\n"
                            "- ✅ `create_pr` — created this PR\n"
                            "- ✅ `review_pr_diff` — reviewed diff\n"
                            "- ✅ `add_issue_comment` — this comment!\n\n"
                            "**Please close this PR manually — test complete.** 🎉"
                        ),
                    },
                )
                r.raise_for_status()
                data = r.json()
                print(f"  ✓ Comment posted: {data['html_url']}")
                results["add_issue_comment"] = "PASS"
        except Exception as e:
            print(f"  ✗ FAIL: {str(e)[:200]}")
            results["add_issue_comment"] = f"FAIL: {str(e)[:200]}"

    # ── Final Report ──
    report(results, pr_number, REPO)


def report(results, pr_number, repo):
    print()
    print("=" * 60)
    print("WORKFLOW TEST RESULTS")
    print("=" * 60)
    all_pass = True
    for step, result in results.items():
        ok = result == "PASS" or result.startswith("PASS")
        icon = "✅" if ok else "❌"
        print(f"  {icon} {step}: {result}")
        if not ok:
            all_pass = False

    print()
    if all_pass:
        print("OVERALL: ALL PASS ✅")
    else:
        print("OVERALL: SOME FAILURES ❌")

    if pr_number:
        print(f"\nPR: https://github.com/{repo}/pull/{pr_number}")
        print("Action: Close this PR manually — merge_pull_request not tested.")


if __name__ == "__main__":
    main()
